/** Curated sample files for the standalone demo page templates dropdown */

interface DemoTemplate {
  name: string;
  text: string;
}

const DEFAULT_TEMPLATE_NAME = 'Full tour';

const DEMO_TEMPLATES: DemoTemplate[] = [
  {
    name: DEFAULT_TEMPLATE_NAME,
    text: [
      '# Tour completo: run any block in the right column.',
      '# Reference: https://github.com/Esl1h/StandardNotes-APIclient',
      '',
      '# Environments: switch the chips in the sidebar. {{token}}',
      '# resolves the active environment first and falls back to the',
      '# default value below.',
      '',
      '@token = default-demo-token',
      '@token.staging = staging-demo-token',
      '@token.prod = prod-demo-token',
      '@env = staging',
      '',
      '### Active environment echo (the header changes per chip)',
      'GET https://httpbin.org/headers',
      'Authorization: Bearer {{token}}',
      '',
      '### Variables in query strings',
      '@client = standardnotes-apiclient',
      'GET https://httpbin.org/get?client={{client}}',
      '',
      '### POST a JSON body',
      'POST https://httpbin.org/post',
      'Content-Type: application/json\n',
      '{"plugin": "standardnotes-apiclient"}',
      '',
      '### Status codes: green >= 400 renders red',
      'GET https://httpbin.org/status/201',
      '',
      '### Slow response: watch the inline timer',
      'GET https://httpbin.org/delay/2',
      '',
      '### CRUD against a real public API (jsonplaceholder)',
      'GET https://jsonplaceholder.typicode.com/posts/1',
    ].join('\n'),
  },
  {
    name: 'CRUD basics',
    text: [
      '# CRUD basics against jsonplaceholder (public fake API).',
      '# Note the ids in the responses: the server fakes writes.',
      '',
      '@base = https://jsonplaceholder.typicode.com',
      '',
      '### List posts (pagination in query)',
      'GET {{base}}/posts?_start=0&_limit=5',
      '',
      '### Read one post',
      'GET {{base}}/posts/1',
      '',
      '### Create a post',
      'POST {{base}}/posts',
      'Content-Type: application/json',
      '',
      '{"title": "hello", "body": "from standardnotes apiclient", "userId": 1}',
      '',
      '### Replace a post',
      'PUT {{base}}/posts/1',
      'Content-Type: application/json',
      '',
      '{"id": 1, "title": "replaced"}',
      '',
      '### Partial update',
      'PATCH {{base}}/posts/1',
      'Content-Type: application/json',
      '',
      '{"title": "patched"}',
      '',
      '### Delete (echoes 200 with {})',
      'DELETE {{base}}/posts/1',
    ].join('\n'),
  },
  {
    name: 'Auth and headers',
    text: [
      '# Auth patterns: httpbin echoes back exactly what you sent.',
      '',
      '@host = https://httpbin.org',
      '',
      '### Bearer token (httpbin /bearer echoes it)',
      'GET {{host}}/bearer',
      'Authorization: Bearer demo-token-123',
      '',
      '### API key + custom headers',
      'GET {{host}}/headers',
      'X-Api-Key: demo-api-key',
      'X-Standard-Notes: api client',
      'Accept: application/json',
      '',
      '### Basic auth header (base64 of demo:demo)',
      'GET {{host}}/headers',
      'Authorization: Basic ZGVtbzpkZW1v',
      '',
      '### What the browser sends by default',
      'GET {{host}}/headers',
    ].join('\n'),
  },
  {
    name: 'Real world APIs',
    text: [
      '# Keyless public APIs you can run from this page.',
      '',
      '@lat = -23.55',
      '@lon = -46.63',
      '',
      '### Weather now (Open-Meteo, São Paulo)',
      'GET https://api.open-meteo.com/v1/forecast?latitude={{lat}}&longitude={{lon}}&current=temperature_2m,wind_speed_10m',
      '',
      '### Random dog photo',
      'GET https://dog.ceo/api/breeds/image/random',
      '',
      '### Random cat fact',
      'GET https://catfact.ninja/fact',
      '',
      '### GitHub: my public repos (change the username variable)',
      '@githubUser = Esl1h',
      'GET https://api.github.com/users/{{githubUser}}/repos?sort=updated&per_page=5',
    ].join('\n'),
  },
];

export type { DemoTemplate };
export { DEMO_TEMPLATES, DEFAULT_TEMPLATE_NAME };
